import type { Metadata } from "next"
import "./globals.css"
import { Open_Sans } from "next/font/google"
import Navbar from "@/components/navbar/Navbar"
import Footer from "@/components/footer/Footer"
import { CartProvider } from "@/context/CartContext"
import { Toaster } from "sonner"

export const metadata: Metadata = {
  title: "Lozach",
  description: "Generated by create next app",
}

const open_sans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${open_sans.className} antialiased`}>
        <CartProvider>
          <Toaster richColors duration={4000} position="top-right" />
          <Navbar />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  )
}
