-- Guía de talles por producto: tabla maestra `size_guides` + FK opcional en `products`.

create table if not exists public.size_guides (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  category text,
  headers jsonb not null default '[]'::jsonb,
  rows jsonb not null default '[]'::jsonb,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'size_guides_name_check'
  ) then
    alter table public.size_guides
      add constraint size_guides_name_check
      check (char_length(trim(name)) > 0);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'size_guides_category_check'
  ) then
    alter table public.size_guides
      add constraint size_guides_category_check
      check (
        category is null
        or category in ('adult', 'child', 'unisex')
      );
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'size_guides_headers_is_array_check'
  ) then
    alter table public.size_guides
      add constraint size_guides_headers_is_array_check
      check (jsonb_typeof(headers) = 'array');
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'size_guides_rows_is_array_check'
  ) then
    alter table public.size_guides
      add constraint size_guides_rows_is_array_check
      check (jsonb_typeof(rows) = 'array');
  end if;
end $$;

create index if not exists size_guides_category_idx
  on public.size_guides (category);

create or replace function public.set_size_guides_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_size_guides_updated_at on public.size_guides;
create trigger set_size_guides_updated_at
  before update on public.size_guides
  for each row execute function public.set_size_guides_updated_at();

alter table public.products
  add column if not exists size_guide_id bigint;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'products_size_guide_id_fkey'
  ) then
    alter table public.products
      add constraint products_size_guide_id_fkey
      foreign key (size_guide_id)
      references public.size_guides (id)
      on delete set null;
  end if;
end $$;

create index if not exists products_size_guide_id_idx
  on public.products (size_guide_id);

-- Row Level Security: lectura pública, escritura sólo admin.
alter table public.size_guides enable row level security;

drop policy if exists "size_guides_select_all" on public.size_guides;
create policy "size_guides_select_all"
  on public.size_guides
  for select
  using (true);

drop policy if exists "size_guides_admin_insert" on public.size_guides;
create policy "size_guides_admin_insert"
  on public.size_guides
  for insert
  with check (
    exists (
      select 1 from public.users u
      where u.id = auth.uid() and u.role = 'admin'
    )
  );

drop policy if exists "size_guides_admin_update" on public.size_guides;
create policy "size_guides_admin_update"
  on public.size_guides
  for update
  using (
    exists (
      select 1 from public.users u
      where u.id = auth.uid() and u.role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.users u
      where u.id = auth.uid() and u.role = 'admin'
    )
  );

drop policy if exists "size_guides_admin_delete" on public.size_guides;
create policy "size_guides_admin_delete"
  on public.size_guides
  for delete
  using (
    exists (
      select 1 from public.users u
      where u.id = auth.uid() and u.role = 'admin'
    )
  );

comment on table public.size_guides is
  'Guías de talles administradas por el equipo y asignables por producto.';
comment on column public.size_guides.headers is
  'Encabezados de columnas de la tabla (ej: ["Talle", "Pecho", "Cintura"]).';
comment on column public.size_guides.rows is
  'Filas de la tabla como arreglo de arreglos de strings, en el mismo orden que headers.';
comment on column public.size_guides.note is
  'Aclaración opcional debajo de la tabla (cómo medir, tolerancia, etc.).';
comment on column public.products.size_guide_id is
  'Guía de talles asignada a este producto. Null = sin guía.';
